openhab:
  state: off
  base_url: 'http://10.0.10.10/rest'
  sensors: 
    OpenCloseCupboardA_SensorDoor:
      - joke:
          question: Why was the kitchen cabinet feeling so stressed out?
          answer: Because it was feeling the weight of all the extra cups of tea it had to make during the holiday season!
      - joke:
          question: Why was the kitchen cabinet feeling so stressed out?
          answer: Because it was trying to keep all the pots, pans, and dishes in order, and it was always "on the shelf" with all its responsibilities!
      - joke:
          question: Why was the first aid kit feeling so important?
          answer: Because it was the band aid that held everything together in an emergency!
      - joke:
          question: Why was the person so excited to open the kitchen cupboard?
          answer: Because they were hoping to find a magic potion that would make all their cooking and cleaning chores disappear!
      - joke:
          question: Why was the person so excited to open the kitchen cupboard?
          answer: Because they had heard a rumor that there was a cupboard monster living inside, and they wanted to see if it was true!
      - joke:
          question: Why was the kitchen cupboard feeling so cluttered and disorganized?
          answer: Because it was filled to the brim with pots, pans, and dishes, and it was feeling crowded and overwhelmed!
      - joke:
          question: Why was the person so surprised to find a first aid kit in the kitchen cabinet?
          answer: Because they were expecting to find something to eat, but instead they found a band aid for their hunger pains!
      - joke:
          question: Why was the person so surprised to find a first aid kit in their kitchen cabinet?
          answer: Because they were expecting to find a "cabinet of cookies" instead, and they ended up feeling "band-aid" about it!
    OpenCloseWindowB_SensorDoor:
      - joke:
          question: Why was the person so excited to open the window on Christmas Day?
          answer: Because they wanted to see if Santa had come down the chimney yet!
      - joke:
          question: Why was the person so excited to open the window on Christmas Day?
          answer: Because they couldn't wait to see if Santa had left any "window" presents!
      - joke:
          question: Why was the window feeling so lonely?
          answer: Because it had no panes!
      - joke:
          question: Why was the window so popular with the insects?
          answer: Because it was always open to new ideas!
      - joke:
          question: Why was the window always so depressed?
          answer: Because it was feeling "glass half empty" all the time!
      - joke:
          question: Why did the person open the window on a cold winter day?
          answer: Because they wanted to let in some fresh air, but they ended up "freezing" their behinds off instead!
      - joke:
          question: Why was the window feeling so chilly on a cold winter day?
          answer: Because it was "frosted" over and couldn't keep the heat in!
      - joke:
          question: Why did the window stay closed all winter?
          answer: Because it was feeling "frosty" and didn't want to let anyone in!
      - joke:
          question: Why was the window feeling so frosty on a cold winter day?
          answer: Because it was covered in a layer of frost and ice, and it was feeling "frosty" and chilled to the bone!

    # OpenCloseCupboardG_SensorDoor:
    #   speech-state-OPEN: "We are running low on cleaning supplies but I have ordered some more." 
    #   speech-state-CLOSED: "Thanks for closing the cupboard" 
    #   turn-state-direction-OPEN: "LEFT"
    #   turn-state-duration-OPEN: 1
    #   turn-state-direction-CLOSED: "RIGHT"
    #   turn-state-duration-CLOSED: 1
    # OpenCloseDoorA_SensorDoor:
    #   speech-state-OPEN: "Someone has entered the room" 
    #   speech-state-CLOSED: "The door has been closed" 
    # OpenCloseWindowB_SensorDoor:
    #   speech-state-OPEN: "There is a lovely breeze coming in through the window." 
    #   speech-state-CLOSED: "Thats nice and warm now" 
      
