openhab:
  state: off
  base_url: 'http://10.0.10.10:8080/rest'
  sensors: 
    'Open Close - Cupboard A':
      speech-state-OPEN: "You are getting the first aid kit? Are you ok?" 
      speech-state-CLOSED: "Thanks for closing the cupboard" 
      turn-state-direction-OPEN: "LEFT"
      turn-state-duration-OPEN: 1
      turn-state-direction-CLOSED: "RIGHT"
      turn-state-duration-CLOSED: 1
    CupboardGSensor_SensorDoor:
      speech-state-OPEN: "We are running low on cleaning supplies but I have ordered some more." 
      speech-state-CLOSED: "Thanks for closing the cupboard" 
      turn-state-direction-OPEN: "LEFT"
      turn-state-duration-OPEN: 1
      turn-state-direction-CLOSED: "RIGHT"
      turn-state-duration-CLOSED: 1
    FrontDoorSensor_SensorDoor:
      speech-state-OPEN: "Someone has entered the room" 
      speech-state-CLOSED: "The door has been closed" 
    WindowBSensor_SensorDoor:
      speech-state-OPEN: "There is a lovely breeze coming in through the window." 
      speech-state-CLOSED: "Thats nice and warm now" 
      