parts:
  warehouse:
    - id: 17
      model: Grabber
      code: white-9-hole-double-bend-beam
      name: White Double Bend Beam
      qty: 10
    - id: 4
      model: Grabber
      code: black-2-hole-2-cross-connector
      name: Black 2 Cross Connector
      qty: 10
    - id: 16
      model: Grabber
      code: dark-grey-2-hole-cross-block
      name: Dark Grey Cross Block
      qty: 10
    - id: 10
      model: Grabber
      code: long-black-axle
      name: Black Axle Length 6
      qty: 10
    - id: 7
      model: Grabber
      code: short-red-axle-connector
      name: Red Axle Connector
      qty: 10
    - id: 2
      model: Grabber
      code: red-notched-axle
      name: Red Notched Axle
      qty: 10
    - id: 6
      model: Grabber
      code: short-grey-axle
      name: Grey Axle Length 3
      qty: 10
    - id: 27
      model: Gyroboy
      code: black-1-hole-beam
      name: Black Cross Beam
      qty: 10
    - id: 24
      model: Gyroboy
      code: black-2-pin-link-tread
      name: Black Tread Link
      qty: 10
    - id: 13
      model: Grabber
      code: red-long-pin-and-bush
      name: Red Pin and Bush
      qty: 10
    - id: 9
      model: Grabber
      code: black-pin
      name: Black Pin
      qty: 10
    - id: 25
      model: Gyroboy
      code: blue-short-axle-pin
      name: Blue Axle Pin
      qty: 10
    - id: 30
      model: Gyroboy
      code: cream-short-axle-pin
      name: Cream Axle Pin
      qty: 10
    - id: 22
      model: Gyroboy
      code: grey-pin-center-hole
      name: Grey Double Pin
      qty: 10
    - id: 23
      model: Gyroboy
      code: ultrasonic-sensor
      name: Ultrasonic Sensor
      qty: 10
    - id: 20
      model: Gyroboy
      code: black-fairing
      name: Black Fairing
      qty: 10
    - id: 12
      model: Grabber
      code: black-angular-wheel
      name: Black Angular Wheel
      qty: 10
    - id: 14
      model: Grabber
      code: long-grey-axle
      name: Grey Axle Length 7
      qty: 10
    - id: 5
      model: Grabber
      code: black-2-hole-1-cross-connector
      name: Black 2 Hole Connector
      qty: 10
    - id: 11
      model: Grabber
      code: black-5-hole-t-shape
      name: Black T-shape
      qty: 10
    - id: 1
      model: Grabber
      code: white-7-hole-l-shape
      name: White L-beam
      qty: 10
    - id: 3
      model: Grabber
      code: medium-grey-axle
      name: Grey Axle Length 5
      qty: 10
    - id: 8
      model: Grabber
      code: yellow-bush
      name: Yellow Bush
      qty: 10
    - id: 19
      model: Gyroboy
      code: long-blue-pin
      name: Long Blue Pin
      qty: 10
    - id: 29
      model: Gyroboy
      code: white-5-hole-bent-beam
      name: White Single Bent Beam
      qty: 10
    - id: 21
      model: Gyroboy
      code: grey-5-hole-beam
      name: Grey Beam
      qty: 10
    - id: 26
      model: Gyroboy
      code: black-7-hole-bent-beam
      name: Black Single Bent Beam
      qty: 10
    - id: 18
      model: Gyroboy
      code: grey-4-pin-cross-beam
      name: Grey Cross Beam
      qty: 10
    - id: 15
      model: Grabber
      code: servo-motor
      name: Servo Motor
      qty: 10
    - id: 31
      model: Grabber
      code: cable-connector
      name: 25 centimetre cable
      qty: 10
    - id: 32
      model: Grabber
      code: grey-pin
      name: Grey pin
      qty: 20
    - id: 33
      model: Grabber
      code: blu-pin
      name: Blue pin
      qty: 20
    - id: 34
      model: Grabber
      code: grey-l-beam
      name: Grey L beam
      qty: 20



