version: "3.9"
services:
  alice:
    build: .
    network_mode: host
    privileged: true
    restart: always
    devices:
      - "/dev/csjbot/arduino:/dev/arduino"
    volumes:
      - .:/root/catkin_ws
