main_connection:
    prod:
        host: '192.168.99.101'
        port: 60001
    dev:
        host: '172.17.0.2'
        port: 60001

video_connection:
    prod:
        host: '192.168.99.101'
        port: 60003
    dev: # NOT YET SUPPORTED IN PSEUDO-LILY
        host: '172.17.0.2'
        port: 60003

